# Generated by Django 5.0 on 2023-12-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_discount_tax_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='stripe_id',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='stripe_id',
        ),
        migrations.AddField(
            model_name='discount',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
