# Generated by Django 5.0 on 2023-12-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_discount_stripe_id_remove_tax_stripe_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.AddField(
            model_name='order',
            name='discounts',
            field=models.ManyToManyField(to='shop.discount'),
        ),
    ]
