# Generated by Django 5.0 on 2023-12-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_currency_order_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='stripe_id',
            field=models.CharField(default='', max_length=100, verbose_name='Идентификатор скидки в Stripe'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_for_view',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Цена товара для отображения'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_stripe',
            field=models.CharField(max_length=100, verbose_name='Идентификатор цены товара в Stripe'),
        ),
    ]
